export interface SupportArticle {
  id: string;
  title: string;
  category: string;
  summary: string;
  content: string;
}

export const SUPPORT_ARTICLES: SupportArticle[] = [
  {
    id: "getting-started",
    title: "Getting started with Atelier: How does the agent coordination work?",
    category: "Getting Started",
    summary: "Learn how the five specialized AI agents coordinate to produce a complete research manuscript.",
    content: `Atelier is a multi-agent research framework that structures scientific writing into an automated pipeline. Instead of a single chatbot answering questions, Atelier coordinates five specialized AI agents, each handling a single phase of research:

1. **Literature Review Agent**: Reads uploaded paper PDFs, extracting key methodologies, findings, objectives, and limitations.
2. **Citation Agent**: Formulates standard bibliography files in APA, IEEE, or BibTeX styles based on the referenced papers.
3. **Research Gap Agent**: Cross-references studies to find unexplored research questions, contradictions, or novelty opportunities.
4. **Methodology Agent**: Recommends appropriate algorithms, mathematical formulations, metrics, and tools.
5. **Report Generator Agent**: Integrates findings from the other four agents into a beautifully structured, publishable manuscript draft.

To start, create a **Topic**, upload the relevant PDFs, and click the **Run Agents** or run each agent step-by-step!`
  },
  {
    id: "agent-roles",
    title: "What does each of the 5 agents do?",
    category: "Agent Info",
    summary: "Detailed descriptions of the roles, responsibilities, and expected outputs of each agent.",
    content: `Each of the five agents in Atelier has a specific function:

*   **Literature Review**: Synthesizes individual papers. It highlights what the paper accomplished, its theoretical framework, and its primary limitations.
*   **Citation**: Automates citation formatting. It creates clean bibliographic records so you don't have to manually format citations.
*   **Research Gap**: Performs comparative analysis. It identifies gaps where current papers fail to address specific parameters or where conflicts exist.
*   **Methodology**: Suggests implementation paths. It recommends specific datasets, algorithms, and models suited to your topic.
*   **Report Generator**: Compiles and writes. It acts as the final editor, compiling the workspace outputs into a polished academic format.

You can run these agents one by one in the topic page, reviewing their output at each step, or chain them together to build a complete report.`
  },
  {
    id: "export-formats",
    title: "How to export your manuscript?",
    category: "Export",
    summary: "Guides you on exporting your research reports into PDF or DOCX formats.",
    content: `Once the agents have completed their runs and you have verified the results, you can export the compiled report.

1.  Open the topic workspace.
2.  Navigate to the **Report Generator** or **Manuscript Preview** tab.
3.  Click the **Export Report** button.
4.  Choose between:
    *   **PDF**: Best for sharing a polished, formatted document.
    *   **DOCX (Word Document)**: Best if you want to make manual edits in Microsoft Word or Google Docs.

All citations and reference sections generated by the **Citation Agent** will be appended to the end of the file automatically.`
  },
  {
    id: "managing-topics",
    title: "Managing topics and papers",
    category: "Workspace",
    summary: "How to create new topics, upload PDFs, index papers, and delete workspaces.",
    content: `Your Atelier workspace is structured around **Topics**:

*   **Creating a Topic**: From the dashboard, click **New Topic**, name it (e.g., \"AI in Education\"), and give it a brief description.
*   **Uploading Papers**: Open your topic workspace, drag and drop paper PDF files, or click the upload area.
*   **Indexing Papers (RAG)**: To enable the search and paper chat, click **Index now**. This converts the PDFs into embedded text chunks for precise querying.
*   **Deleting Items**: You can delete individual papers or remove the entire topic workspace from the dashboard using the delete button.`
  },
  {
    id: "troubleshooting",
    title: "Troubleshooting rate limits and errors",
    category: "Troubleshooting",
    summary: "Resolve common questions about Gemini API limits and paper ingestion errors.",
    content: `If you run into issues while indexing papers or running agents:

*   **Gemini Rate Limit Exceeded**: If you see a rate limit message (429), it means the API has received too many requests in a short period. Wait 1-2 minutes and try again.
*   **PDF Ingestion Failed**: Ensure the PDF is not password-protected and contains copyable text. Scanned images of text might fail to index if they don't have OCR text layers.
*   **Agent Failure**: If an agent stops responding, check your internet connection, refresh the page, and try running the step again.`
  }
];
